services:
  - type: web
    name: birdbuddy
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: "7860"
      - key: GRADIO_SERVER_NAME
        value: "0.0.0.0"
      - key: GRADIO_SERVER_PORT
        value: "7860"

